# -*- coding: utf-8 -*-

from odoo import models, fields

class Route(models.Model):
    """
    Model that represents a route of the Camino de Santiago.
    """
    _name = 'bookings.route'
    _description = 'Represents a route of the Camino de Santiago'

    # -- Table fields --
    name = fields.Char(string='Name', required=True)
    distance = fields.Float(string="Distance") # Not real distance
    url_maps = fields.Char() # Must be autogenerated
    description = fields.Text()

    # -- Relations --
    # Related landmarks to the current route
    related_landmarks_ids = fields.One2many('bookings.landmark_by_route', 'route_id')

    # Related lodgins to the current route
    related_lodgins_ids = fields.Many2many(
        comodel_name='bookings.lodgin',
        relation='bookings_lodgin_by_route',
        column1='route_id',
        column2='lodgin_id',
        string='Lodgins founded'
    )
    
    # -- Functions --
    # Returns the name of the Route
    def name_get(self):
        return [(rec.id, rec.name) for rec in self]